### ISSUE TITLE
Spotifyのライブラリ導入について

### ISSUE THREAD

**Issue by Komei22** [pepabo-mobile-app-training/spotter#38]
### SpotifyLoginライブラリの問題点
[SpotifyLogin](https://github.com/spotify/SpotifyLogin/blob/master/Sources/SpotifyLogin.swift)のライブラリでは、ログインとログアウトの機能のみを提供している。そのため、access_tokenが期限切れになった場合、再度spotifyのログイン画面に飛んでログイン処理を行わなければならないためユーザビリティが損なわれると考えられる。

### spotify/ios-sdkライブラリについて
[spotify/ios-sdk](https://github.com/spotify/ios-sdk)では、前述した問題点を解消する事ができる。spotifyAPIでは認証リクエストのレスポンスとして、access_tokenとrefresh_tokenを返す。access_tokenが一定時間で期限切れになった場合はrefresh_tokenを使って新しいaccess_tokenを取得することでログイン処理を省略できる。
この機能はios-sdkの[SPTAuth](https://spotify.github.io/ios-sdk/Classes/SPTAuth.html)の`renewsession`で提供されており、これを利用することで実現できると思われる。
一方、SpotifyLoginライブラリの場合、前述したrefresh_tokenを利用した仕組みを作らなければならないため工数が増えると考えられる。

したがって、spotify/ios-sdkライブラリを採用する方向で進めたいと考えている。

参考issue：https://github.com/pepabo-mobile-app-training/spotter/issues/7

**Comment by Asuforce** [comment]
ref: https://github.com/spotify/SpotifyLogin/blob/master/Sources/SpotifyLogin.swift#L62
上記を見る限り、自動で更新すると書いてありますが、そうではないという事なんですかね？

**Comment by Komei22** [comment]
その記述見逃していました。。。
コード読み直してみたら、
https://github.com/spotify/SpotifyLogin/blob/master/Sources/SpotifyLogin.swift#L81
この記述がrefresh_tokenを使ったaccess_token取得処理をしているようなのでSpotifyLoginで実装するほうが簡単だと思いました。
なのでSpotifyLoginを採用したいと思います。
